version: "3.9"

services:
  parker-frontend:
    image: ${IMAGE_TAG}
    ports:
      - "8086:80"
    networks:
      - pms-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  pms-net:
    driver: overlay
